id: I71481181
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T08:24:15+00:00'
last_modified: '2022-06-08T17:15:01.441338+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23860
  title: གསུང་འབུམ། རྡོ་རྗེ་རྒྱལ་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EEF2:
      image_group_id: I3003
      title: ''
      total_pages: 1038
      order: 1
      base_file: EEF2.txt
    3D57:
      image_group_id: I3004
      title: ''
      total_pages: 968
      order: 2
      base_file: 3D57.txt
    824F:
      image_group_id: I3005
      title: ''
      total_pages: 1034
      order: 3
      base_file: 824F.txt
    F8F4:
      image_group_id: I3006
      title: ''
      total_pages: 950
      order: 4
      base_file: F8F4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
