id: I71481181
legacy_id: P010749
ocr_import_info:
  bdrc_scan_id: W23860
  source: bdrc
  ocr_info:
    timestamp: '2021-01-19T09:13:26'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T04:51:20.633402+00:00'
last_modified: 2022-09-02 12:52:22.270213
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23860
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23860
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། རྡོ་རྗེ་རྒྱལ་པོ།
  author: ཕག་མོ་གྲུ་པ་རྡོ་རྗེ་རྒྱལ་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.8274287501499591
  ocr_word_median_confidence_index: 0.9
quality: null
bases:
  I3004:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3004
      total_pages: 968
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3004.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.5400000003476938
    legacy_id: v002
  I3005:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3005
      total_pages: 1034
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3005.txt
    statistics:
      ocr_word_median_confidence_index: 0.9
      ocr_word_mean_confidence_index: 0.8276134383075906
    legacy_id: v003
  I3003:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3003
      total_pages: 1038
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3003.txt
    statistics:
      ocr_word_median_confidence_index: 0.78
      ocr_word_mean_confidence_index: 0.7347692307692307
    legacy_id: v001
  I3006:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3006
      total_pages: 950
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3006.txt
    legacy_id: v004
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
