id: P010749
initial_creation_type: ocr
source_metadata:
  id: bdr:W23860
  title: གསུང་འབུམ། རྡོ་རྗེ་རྒྱལ་པོ
  author: ''
  volumes:
    17da5193a18b470c820f68c1fbc9a200:
      image_group_id: I3003
      title: ''
      volume_number: 1
      total_pages: 1038
    664b61243fc541bf8a574f02bae37170:
      image_group_id: I3004
      title: ''
      volume_number: 2
      total_pages: 968
    f4b0a57e9a3b420599f4b820e0feda82:
      image_group_id: I3005
      title: ''
      volume_number: 3
      total_pages: 1034
    4eccc5afb8004dbb854ff1d7891d7fa7:
      image_group_id: I3006
      title: ''
      volume_number: 4
      total_pages: 950
